set(CLANG_COMMON_WARNINGS "-Wall -Wextra")

set(CLANG_COMMON_C_FLAGS "${CLANG_COMMON_WARNINGS}")
set(CLANG_COMMON_CXX_FLAGS "${CLANG_COMMON_WARNINGS}")

function(apply_clang_common_flags)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CLANG_COMMON_C_FLAGS}" PARENT_SCOPE)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CLANG_COMMON_CXX_FLAGS}" PARENT_SCOPE)
endfunction()

